name: Tests

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["master"]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  test:
    name: Build and test (Swift ${{ matrix.swift }} on ${{ matrix.os }})
    strategy:
      matrix:
        tests:
          - xcode: '14.2'
            machine: macos-12
          - xcode: '14.3.1'
            machine: macos-13
    runs-on: ${{ matrix.tests.machine }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.tests.xcode }}.app

      - name: Build and Test SPM
        run: swift test --enable-code-coverage

      - name: Update Cocoa Pods repo
        run: pod repo update

      - name: Build and Test CocoaPods
        run: pod lib lint --allow-warnings --fail-fast

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
